### ISSUE TITLE
"target/scala-2.10/proguard/merged/LICENSE" directory not merging

### ISSUE THREAD

**Issue by DynamicScope** [sbt/sbt-proguard#15]
I am getting the following error.

```
[info] Merging inputs before proguard...
[error] /my/project/target/scala-2.10/proguard/merged/LICENSE (Is a directory)
java.lang.RuntimeException: Failed to merge all inputs. Merge strategies can be used to resolve conflicts.
       	at scala.sys.package$.error(package.scala:27)
       	at com.typesafe.sbt.proguard.Merge$$anonfun$merge$1.apply(Merge.scala:81)
       	at com.typesafe.sbt.proguard.Merge$$anonfun$merge$1.apply(Merge.scala:67)
       	at sbt.IO$.withTemporaryDirectory(IO.scala:291)
       	at com.typesafe.sbt.proguard.Merge$.merge(Merge.scala:67)
       	at com.typesafe.sbt.SbtProguard$ProguardSettings$$anonfun$mergeTask$1$$anonfun$1.apply(SbtProguard.scala:86)
       	at com.typesafe.sbt.SbtProguard$ProguardSettings$$anonfun$mergeTask$1$$anonfun$1.apply(SbtProguard.scala:82)
       	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
       	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
       	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:249)
       	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:245)
       	at sbt.Difference.apply(Tracked.scala:224)
       	at sbt.Difference.apply(Tracked.scala:206)
       	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:245)
       	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:244)
       	at sbt.Difference.apply(Tracked.scala:224)
       	at sbt.Difference.apply(Tracked.scala:200)
       	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:244)
       	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:242)
       	at com.typesafe.sbt.SbtProguard$ProguardSettings$$anonfun$mergeTask$1.apply(SbtProguard.scala:90)
       	at com.typesafe.sbt.SbtProguard$ProguardSettings$$anonfun$mergeTask$1.apply(SbtProguard.scala:80)
       	at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:35)
       	at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:34)
       	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
       	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
       	at sbt.std.Transform$$anon$4.work(System.scala:63)
       	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
       	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
       	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
       	at sbt.Execute.work(Execute.scala:235)
       	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
       	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
       	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
       	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
       	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
       	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       	at java.lang.Thread.run(Thread.java:745)
[error] (proguard:mergedInputs) Failed to merge all inputs. Merge strategies can be used to resolve conflicts.
```

And I've tried the followings...

```
ProguardKeys.merge in Proguard := true
ProguardKeys.mergeStrategies in Proguard += ProguardMerge.discard("license/.*".r)
```
and
```
ProguardKeys.merge in Proguard := true
ProguardKeys.mergeStrategies in Proguard += ProguardMerge.append("license")
```

None of above are working. Are there anything wrong about the merge strategies?

Thank you.

**Comment by DynamicScope** [comment]
`ProguardKeys.mergeStrategies in Proguard += ProguardMerge.rename("LICENSE.*".r)`

rename() did the job~!!
