### ISSUE TITLE
How to be able to json serialize case classes?

### ISSUE THREAD

**Issue by sejsworld** [sbt/sbt-proguard#27]
Hi, 

I am trying to build our aws lambda functions in scala and have a case class and uses io.circe for json and it fails. Cold starts on aws lambda is about af factor 4 with proguard working, so its a really painpont.

I think I have tried almost every combination of proguard konfiguration and are not able to figure out how to remove this error :-( whenever I change the konfiguration a new error arises

Among tested konfiguration parameters are 
-keepattributes EnclosingMethod,InnerClasses,Signature
-keepattributes *Annotation*
-keepclassmembers class ** {

Stacktrace
Loading Java Lambda handler of ProxyWithStreamjava.lang.BootstrapMethodError: call site initialization exception
	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at com.ProxyWithStream$anon$exportEncoder$macro$48$1.inst$macro$1$lzycompute(ChallengesService.scala:84)
	at com.ProxyWithStream$anon$exportEncoder$macro$48$1.inst$macro$1(ChallengesService.scala:84)
	at com.ProxyWithStream.handleRequest(ChallengesService.scala:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.lang.NoSuchMethodException: no such method: scala.Symbol.apply(Object)Object/invokeStatic
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:871)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1003)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1386)
	at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:780)
	at scala.runtime.SymbolLiteral.bootstrap(SymbolLiteral.java:15)
	at java.lang.invoke.CallSite.makeSite(CallSite.java:294)
	... 9 more
Caused by: java.lang.NoSuchMethodError: scala.Symbol.apply(Ljava/lang/Object;)Ljava/lang/Object;
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
	... 13 more

lambda code and case class is mostly strings the error happens in the asJson call for val challengeJson = ....

import io.circe.generic.auto._, io.circe.syntax._
class ProxyWithStream extends RequestStreamHandler {
  
  @throws[IOException]
  override def handleRequest(inputStream: InputStream, outputStream: OutputStream, context: Context): Unit = {
    val logger = context.getLogger
    logger.log("Loading Java Lambda handler of ProxyWithStream")
    val reader = new BufferedReader(new InputStreamReader(inputStream))
    var responseJson = ""
    try {

      val challengeUuid = UUID.randomUUID().toString
      val userUuid = UUID.randomUUID().toString

      val challenge = Challenge(challengeUuid, ...)

      val challengeJson = challenge.asJson.noSpaces
      responseJson = ApiGatewayResponse(challengeJson).asJson.noSpaces
    } catch {
      case pex: Exception =>
      logger.log(s"error: $pex")
    }
    logger.log(responseJson)
    val writer = new OutputStreamWriter(outputStream, "UTF-8")
    writer.write(responseJson)
    writer.close()  
  }
}

Thank you very much in advance!!

**Comment by sejsworld** [comment]
The solution were more simpel than I would like :-)

Configuration...

proguardOptions in Proguard += "-dontoptimize"

proguardOptions in Proguard ++= Seq("-dontnote", "-dontwarn", "-ignorewarnings", "-dontobfuscate",
"-keepattributes EnclosingMethod,InnerClasses,Signature",
"-keepattributes *Annotation*",
"-keepclassmembers class ** { @com.MyClass public *; }",
"-keep class com.ProxyWithStream { *; }",
"-keep class scala.ScalaObject { *; }",
"-keep class scala.Symbol { *; }")

**Comment by bantonsson** [comment]
Hi @sejsworld, seems like you solved your problem. If that's not the case please reopen this issue.
