### ISSUE TITLE
Error merging on OS Windows 7

### ISSUE THREAD

**Issue by akileev** [sbt/sbt-proguard#6]
I run:

```
 sbt proguard:proguard
```

build.sbt

```
proguardSettings

ProguardKeys.options in Proguard ++= Seq("-dontnote", "-dontwarn", "-ignorewarnings")

ProguardKeys.options in Proguard += ProguardOptions.keepMain("test.MainClass")

inConfig(Proguard)(javaOptions in ProguardKeys.proguard := Seq("-Xmx2g"))

ProguardKeys.merge in Proguard := true

ProguardKeys.mergeStrategies in Proguard += ProguardMerge.append("reference.conf")
```

Output:

```
[info] Loading project definition from C:\projects\home\ProjectName\project
[info] Set current project to ProjectName (in build file:/C:/projects/home/ProjectName/)
[info] Merging inputs before proguard...
java.lang.RuntimeException: Could not create directory C:\Users\A18E6~1.KIL\AppData\Local\Temp\sbt_8fa3b8a3\C:\projects\home\ProjectName\libs\jna-4.1.0.jar
    at scala.sys.package$.error(package.scala:27)
    at sbt.IO$.createDirectory(IO.scala:155)
    at sbt.IO$.unzipStream(IO.scala:192)
    at sbt.IO$$anonfun$unzip$1.apply(IO.scala:187)
    at sbt.IO$$anonfun$unzip$1.apply(IO.scala:187)
    at sbt.Using.apply(Using.scala:25)
    at sbt.IO$.unzip(IO.scala:187)
    at com.typesafe.sbt.proguard.Merge$$anonfun$entries$1.apply(Merge.scala:40)
    at com.typesafe.sbt.proguard.Merge$$anonfun$entries$1.apply(Merge.scala:37)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
    at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
    at com.typesafe.sbt.proguard.Merge$.entries(Merge.scala:37)
    at com.typesafe.sbt.proguard.Merge$$anonfun$merge$1.apply(Merge.scala:69)
    at com.typesafe.sbt.proguard.Merge$$anonfun$merge$1.apply(Merge.scala:67)
    at sbt.IO$.withTemporaryDirectory(IO.scala:285)
    at com.typesafe.sbt.proguard.Merge$.merge(Merge.scala:67)
    at com.typesafe.sbt.SbtProguard$ProguardSettings$$anonfun$mergeTask$1$$anonfun$1.apply(SbtProguard.scala:86)
    at com.typesafe.sbt.SbtProguard$ProguardSettings$$anonfun$mergeTask$1$$anonfun$1.apply(SbtProguard.scala:82)
    at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:188)
    at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:188)
    at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:202)
    at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:198)
    at sbt.Difference.apply(Tracked.scala:177)
    at sbt.Difference.apply(Tracked.scala:158)
    at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:198)
    at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:197)
    at sbt.Difference.apply(Tracked.scala:177)
    at sbt.Difference.apply(Tracked.scala:152)
    at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:197)
    at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:195)
    at com.typesafe.sbt.SbtProguard$ProguardSettings$$anonfun$mergeTask$1.apply(SbtProguard.scala:90)
    at com.typesafe.sbt.SbtProguard$ProguardSettings$$anonfun$mergeTask$1.apply(SbtProguard.scala:80)
    at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:35)
    at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
[error] (proguard:mergedInputs) Could not create directory C:\Users\A18E6~1.KIL\AppData\Local\Temp\sbt_8fa3b8a3\C:\projects\home\ProjectName\libs\jna-4.1.0.jar
[error] Total time: 1 s, completed 19.11.2014 13:31:55
```

**Comment by s-trooper** [comment]
seems to be a simple bug in Merge.scala line 39:
val unzipped = tmp / source.getCanonicalPath

sadly i have no idea of forking or pull request and such stuff

**Comment by concerned3rdparty** [comment]
Same problem on windows 8.1.
